services:
  komga-suwa-sync:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: komga-suwa-sync
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./public:/app/public:ro
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    user: "1000:1000"  # Use host user ID instead of container appuser
    networks:
      - sync-network

networks:
  sync-network:
    driver: bridge
