version: '3.8'

services:
  komga-suwa-sync:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: komga-suwa-sync
    expose:
      - "3000"
    volumes:
      - komga-suwa-data:/app/data
      - ./.env:/app/.env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - komga-suwa-network
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    container_name: komga-suwa-nginx
    ports:
      - "80:80"
      - "443:443"  # For SSL (uncomment ssl configuration in nginx.conf)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./ssl:/etc/nginx/ssl:ro  # Mount SSL certificates here
    depends_on:
      - komga-suwa-sync
    restart: unless-stopped
    networks:
      - komga-suwa-network

networks:
  komga-suwa-network:
    driver: bridge

volumes:
  komga-suwa-data:
    driver: local
